# Generated by Django 4.0.6 on 2022-08-09 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(null=True)),
                ('balance', models.IntegerField(null=True)),
                ('receipt_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='emergency_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(choices=[('A', 'AdaLab'), ('B', 'AnitaB'), ('H', 'HopperLab')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='TeachersPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('unit_specialty', models.CharField(choices=[('P', 'Python'), ('K', 'Kotlin'), ('fw', 'Frontend web'), ('IOT', 'Internet Of Things'), ('UXR', 'User Research'), ('UI/UX', 'UI/UX Design'), ('PD', 'Proffessional Development'), ('NYJ', 'Navigate Your Journey')], max_length=5, null=True)),
                ('contacts', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TeachersPanel_School', to='Schoolsystem.school')),
            ],
        ),
        migrations.CreateModel(
            name='StudentId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StudentId_Student', to='Schoolsystem.student')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('unit_specialty', models.CharField(choices=[('Chef', 'Chef'), ('Cook', 'Cook'), ('Matron', 'Matron'), ('Garderner', 'Gardener'), ('GateKeeper', 'GateKeeper'), ('Accountant', 'Accountant'), ('Lead', 'CodeHive Lead'), ('Event', 'Event Planner'), ('Nurse', 'Nurse')], max_length=10, null=True)),
                ('contacts', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Staff_School', to='Schoolsystem.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_fees', models.IntegerField(null=True)),
                ('amount_paid', models.IntegerField(null=True)),
                ('balance', models.IntegerField(null=True)),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SchoolFees_Receipt', to='Schoolsystem.receipt')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SchoolFees_Student', to='Schoolsystem.student')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=25, null=True)),
                ('account_number', models.IntegerField(max_length=35, null=True)),
                ('School', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SchoolAccount_School', to='Schoolsystem.school')),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='school_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_SchoolAccount', to='Schoolsystem.schoolaccount'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_Student', to='Schoolsystem.student'),
        ),
        migrations.CreateModel(
            name='LibraryManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LibraryManagement_Student', to='Schoolsystem.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B+'), ('B', 'B'), ('B', 'B-'), ('C', 'C+'), ('C', 'C'), ('C', 'C-'), ('D', 'D'), ('E', 'E')], max_length=5, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AcademicAnalysis_Student', to='Schoolsystem.student')),
            ],
        ),
    ]
