# Generated by Django 4.0.6 on 2022-08-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolsystem', '0002_receipt_alter_school_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='unit_specialty',
            new_name='Occupation_specialty',
        ),
    ]
