# Generated by Django 4.0.6 on 2022-08-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolsystem', '0003_rename_unit_specialty_staff_occupation_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
