# Generated by Django 4.1 on 2022-08-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolsystem', '0005_alter_schoolaccount_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(choices=[('AdaLab', 'AdaLab'), ('AnitaB', 'AnitaB'), ('HopperLab', 'HopperLab')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacherspanel',
            name='unit_specialty',
            field=models.CharField(choices=[('Python', 'Python'), ('Kotlin', 'Kotlin'), ('fw', 'Frontend web'), ('IOT', 'Internet Of Things'), ('UXR', 'User Research'), ('UI/UX', 'UI/UX Design'), ('PD', 'Proffessional Development'), ('NYJ', 'Navigate Your Journey')], max_length=6, null=True),
        ),
    ]
