# Generated by Django 4.1 on 2022-08-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolsystem', '0006_alter_student_gender_alter_student_stream_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicanalysis',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B+'), ('B', 'B'), ('B', 'B-'), ('C', 'C+'), ('C', 'C'), ('C', 'C-'), ('D', 'D'), ('E', 'E')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Occupation_specialty',
            field=models.CharField(choices=[('Chef', 'Chef'), ('Cook', 'Cook'), ('Matron', 'Matron'), ('Garderner', 'Gardener'), ('GateKeeper', 'GateKeeper'), ('Accountant', 'Accountant'), ('Lead', 'CodeHive Lead'), ('Event', 'Event Planner'), ('Nurse', 'Nurse')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to  say', 'Prefer not to say')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='teacherspanel',
            name='unit_specialty',
            field=models.CharField(choices=[('Python', 'Python'), ('Kotlin', 'Kotlin'), ('frontend web', 'Frontend web'), ('IOT', 'Internet Of Things'), ('User Research', 'User Research'), ('UI/UX Design', 'UI/UX Design'), ('Proffessional Development', 'Proffessional Development'), ('Navigate Your Journey', 'Navigate Your Journey')], max_length=25, null=True),
        ),
    ]
